spring:
  datasource:
    username: user1
    url: jdbc:oracle:thin:@localhost:1521:orcl
    password: '1234'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
